/*** contacts information ***/
export const GET_CONTACTS_LIST = "GET_CONTACTS_LIST";
export const POST_CREATE_CONTACT = "POST_CREATE_CONTACT";
export const POST_UPDATE_CONTACT = "POST_UPDATE_CONTACT";
export const POST_DELETE_CONTACT = "POST_DELETE_CONTACT";
export const SET_CONTACTS_LIST = "SET_CONTACTS_LIST";
export const SET_CONTACTS_SEARCH_INPUT_TEXT = "SET_CONTACTS_SEARCH_INPUT_TEXT";

/*** general ***/
export const SET_SHOW_LOADER = "SET_SHOW_LOADER";

/*** modal ***/
export const SET_CONTACT_MODAL_OPENED = "SET_CONTACT_MODAL_OPENED";
export const SET_CONTACT_MODAL_VALUE = "SET_CONTACT_MODAL_VALUE";
export const SET_ACTIVE_CONTACT = "SET_ACTIVE_CONTACT";
