/*** contacts information ***/
export const GET_CONTACTS_LIST = "GET_CONTACTS_LIST";
export const POST_CONTACTS_LIST = "POST_CONTACTS_LIST";
export const POST_UPDATE_CONTACT = "POST_UPDATE_CONTACT";
export const SET_CONTACTS_LIST = "SET_CONTACTS_LIST";
export const SET_CONTACTS_SEARCH_INPUT_TEXT = "SET_CONTACTS_SEARCH_INPUT_TEXT";
export const SET_ADD_CONTACT_INPUT_VALUE = "SET_ADD_CONTACT_INPUT_VALUE";
export const SET_ADD_CONTACTS_LIST = "SET_ADD_CONTACTS_LIST";

/*** general ***/
export const SET_ACTIVE_CONTACT = "SET_ACTIVE_CONTACT";
